# Generated by Django 4.2.5 on 2023-09-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_amount_item_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='amount',
        ),
    ]
